In [11]:
# @title Importação das Bibliotecas Necessárias
import numpy as np # manipulação de números, vetores e matrizes
import sympy as sp # cálculos diferenciais, derivadas e integrais

In [5]:
# @title Álgebra Linear - Soma de Matrizes e Vetores
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
print(f'A SOMA entre a matriz A e a matriz B é: \n{C}')

A SOMA entre a matriz A e a matriz B é: 
[[ 6  8]
 [10 12]]


In [6]:
# @title Álgebra Linear - Multiplicação de Matriz por Escalar
A = np.array([[1, 2], [3, 4]])
scalar = 2
C = scalar * A
print(f'A MULTIPLICAÇÃO entre a matriz A e lambda(scalar) é:\n {C}')

A MULTIPLICAÇÃO entre a matriz A e lambda(scalar) é:
 [[2 4]
 [6 8]]


In [8]:
# @title Álgebra Linear - Multiplicação Matricial
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.dot(A, B)  # Ou A @ B
print(f'A MULTIPLICAÇÃO entre a matriz A e a matriz B é:\n{C}')


A MULTIPLICAÇÃO entre a matriz A e a matriz B é:
[[19 22]
 [43 50]]


In [9]:
# @title Álgebra Linear - Transposição de Matrizes
A = np.array([[1, 2], [3, 4]])
A_T = A.T
print(f'A matriz transposta de A é: \n{A_T}')

A matriz transposta de A é: 
[[1 3]
 [2 4]]


In [12]:
# @title Cálculo Diferencial -  Derivadas Parciais
# Definindo as variáveis
x, y = sp.symbols('x y')

# Definindo a função
f = x**2 + 3*x*y + y**2

# Cálculo das derivadas parciais
df_dx = sp.diff(f, x)
df_dy = sp.diff(f, y)

print("Derivada parcial em relação a x:", df_dx)
print("Derivada parcial em relação a y:", df_dy)

Derivada parcial em relação a x: 2*x + 3*y
Derivada parcial em relação a y: 3*x + 2*y


In [13]:
# @title Gradiente Descendente
def mse(y_real, y_pred):
    return np.mean((y_real - y_pred) ** 2)

def gradient(y_real, y_pred, x):
    return -2 * np.mean((y_real - y_pred) * x)

# Inicialização
w = 0
alpha = 0.1
num_steps = 10
y_real = np.array([3, 5, 7, 9])
x = np.array([1, 2, 3, 4])

for i in range(num_steps):
    y_pred = w * x
    grad = gradient(y_real, y_pred, x)
    w = w - alpha * grad
    print(f"Passo {i+1}: w = {w:.4f}, MSE = {mse(y_real, y_pred):.4f}")

Passo 1: w = 3.5000, MSE = 41.0000
Passo 2: w = 1.7500, MSE = 10.3750
Passo 3: w = 2.6250, MSE = 2.7188
Passo 4: w = 2.1875, MSE = 0.8047
Passo 5: w = 2.4062, MSE = 0.3262
Passo 6: w = 2.2969, MSE = 0.2065
Passo 7: w = 2.3516, MSE = 0.1766
Passo 8: w = 2.3242, MSE = 0.1692
Passo 9: w = 2.3379, MSE = 0.1673
Passo 10: w = 2.3311, MSE = 0.1668
