In [1]:
# @title Importação das Bibliotecas Necessárias
import numpy as np
import pandas as pd

In [2]:
# @title Carregamento e Padronização dos Dados
# Criação de um DataFrame de exemplo
data = {
    'F1': [1, 5, 1, 5, 8],
    'F2': [2, 5, 4, 3, 1],
    'F3': [3, 6, 2, 2, 2],
    'F4': [4, 7, 3, 1, 2]
}
df = pd.DataFrame(data)

# Padronização dos dados (subtraindo a média e dividindo pelo desvio padrão)
df_standardized = (df - df.mean()) / df.std()

In [3]:
# @title Cálculo da Matriz de Covariância

# Calculando a matriz de covariância
cov_matrix = np.cov(df_standardized, rowvar=False)

In [8]:
# @title Cálculo dos Autovalores e Autovetores
# Calculando autovalores e autovetores
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print(f'\n Os autovalores são: {eigenvalues}')
print(f'\n Os autovetores são:\n {eigenvectors}')


 Os autovalores são: [2.51579324 1.0652885  0.39388704 0.02503121]

 Os autovetores são:
 [[ 0.16195986 -0.91705888 -0.30707099  0.19616173]
 [-0.52404813  0.20692161 -0.81731886  0.12061043]
 [-0.58589647 -0.3205394   0.1882497  -0.72009851]
 [-0.59654663 -0.11593512  0.44973251  0.65454704]]


In [9]:
# @title Ordenação dos Autovalores e Seleção dos Componentes Principais

# Ordenando autovalores e autovetores
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

print(f'\n Os autovalores são: {eigenvalues}')
print(f'\n Os autovetores são:\n {eigenvectors}')

# Calculando a variância explicada
explained_variance_ratio = eigenvalues / eigenvalues.sum()


 Os autovalores são: [2.51579324 1.0652885  0.39388704 0.02503121]

 Os autovetores são:
 [[ 0.16195986 -0.91705888 -0.30707099  0.19616173]
 [-0.52404813  0.20692161 -0.81731886  0.12061043]
 [-0.58589647 -0.3205394   0.1882497  -0.72009851]
 [-0.59654663 -0.11593512  0.44973251  0.65454704]]


In [20]:
# @title Transformação dos Dados para o Novo Espaço
# Transformando os dados
eigenvectors_selected = eigenvectors[:, :2]
print(f'As duas colunas selecionadas: \n {eigenvectors_selected}')
df_pca = np.dot(df_standardized, eigenvectors_selected)

# Convertendo o resultado para um DataFrame para melhor visualização
df_pca = pd.DataFrame(df_pca, columns=[f'PC{i+1}' for i in range(df_pca.shape[1])])

As duas colunas selecionadas: 
 [[ 0.16195986 -0.91705888]
 [-0.52404813  0.20692161]
 [-0.58589647 -0.3205394 ]
 [-0.59654663 -0.11593512]]


In [22]:
# @title Visualização dos Resultados
# Exibindo a variância explicada por cada componente principal
print("Variância explicada por cada componente principal:")
print(explained_variance_ratio)

# Exibindo os dados transformados
print("\nDados transformados:")
print(f'{df_standardized} \n\n  {eigenvectors_selected} \n\n {df_pca}')

Variância explicada por cada componente principal:
[0.62894831 0.26632213 0.09847176 0.0062578 ]

Dados transformados:
         F1        F2        F3        F4
0 -1.000000 -0.632456  0.000000  0.260623
1  0.333333  1.264911  1.732051  1.563740
2 -1.000000  0.632456 -0.577350 -0.173749
3  0.333333  0.000000 -0.577350 -1.042493
4  1.333333 -1.264911 -0.577350 -0.608121 

  [[ 0.16195986 -0.91705888]
 [-0.52404813  0.20692161]
 [-0.58589647 -0.3205394 ]
 [-0.59654663 -0.11593512]] 

         PC1       PC2
0  0.014003  0.755975
1 -2.556534 -0.780432
2 -0.051480  1.253135
3  1.014150  0.000239
4  1.579861 -1.228917
